package gov.hhs.acf.cb.nytds.persistence.entity;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

/*
 * AggregateLevelError generated by hbm2java
 */
public class AggregateLevelError extends NytdError {
    public String formatErrorMessage() {
        if (problemDescription == null) {
            return "N/A";
        }

        Map<String, Object> namedParams = new HashMap<>();
        Element element = nonCompliance.getDataAggregate().getElement();
        BigDecimal complianceRate = getNonCompliance().getDataAggregate().getPercentValue();
   //     complianceRate = BigDecimal.valueOf(100).subtract(complianceRate);
        namedParams.put("elementNumber", element.getId());
        namedParams.put("elementDescription", element.getDescription());
        namedParams.put("complianceRate", complianceRate);
        String errorMsg = problemDescription.formatText(
                problemDescription.getName(), namedParams);
        return errorMsg;
    }
}
