package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import java.math.BigDecimal;

/*
 * AggregateValue generated by hbm2java
 */
@Entity
public class AggregateValue extends BaseEntity {
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    private Integer countValue;
    @Getter
    @Setter
    private BigDecimal percentValue;

    public AggregateValue() {
    }


}
