package gov.hhs.acf.cb.nytds.persistence.entity;

//Generated Jul 15, 2009 11:56:32 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import java.util.HashSet;
import java.util.Set;


/*
 * * Allowedvalueinconsistency generated by hbm2java
 */
@Entity
public class AllowedValueInconsistency extends BaseEntity
{
	@Getter	@Setter
	private AllowedValue allowedValue;
	@Getter	@Setter
	private ProblemDescription problemDescription;
	@Getter	@Setter
	private Boolean isTrue;
	@Getter	@Setter
	private Set<CrossRefInconsistency> crossRefInconsistencies = new HashSet<>(0);

	public AllowedValueInconsistency()
	{
	}

	public AllowedValueInconsistency(Long allowedValueInconsistencyId)
	{
		this.id = allowedValueInconsistencyId;
	}
	
	public AllowedValueInconsistency(Long allowedValueInconsistencyId, AllowedValue allowedValue,
			ProblemDescription problemdescriptionid, Boolean isTrue,
			Set<CrossRefInconsistency> crossRefInconsistencies)
	{
		super();
		this.id = allowedValueInconsistencyId;
		this.allowedValue = allowedValue;
		this.problemDescription = problemdescriptionid;
		this.isTrue = isTrue;
		this.crossRefInconsistencies = crossRefInconsistencies;
	}





}
