package gov.hhs.acf.cb.nytds.persistence.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import java.util.Calendar;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * AllowedValue generated by hbm2java
 */
@Entity
public class AllowedValue extends BaseEntity {
    @Getter
    @Setter
    @ManyToOne
    private Population population;
    @Getter
    @Setter
    @ManyToOne
    private ElementLevelDQAStandard elementLevelDQAStandard;
    @Getter
    @Setter
    @ManyToOne
    private Element element;
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    private String value;

    public AllowedValue() {
    }

    public AllowedValue(Long allowedValueId) {
        this.id = allowedValueId;
    }

    public AllowedValue(Long allowedValueId, Population population, ElementLevelDQAStandard elementLevelDQAStandard, Element element, String name,
                        String value, Calendar createdDate, String createdBy, Calendar updateDate, String updateBy,
                        String description) {
        this.id = allowedValueId;
        this.population = population;
        //	this.dataQualityAdvStandard = dataQualityAdvStandard;
        this.elementLevelDQAStandard = elementLevelDQAStandard;
        this.element = element;
        this.name = name;
        this.value = value;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
    }

}
