package gov.hhs.acf.cb.nytds.persistence.entity;

//Generated Jul 15, 2009 11:56:32 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Set;


/*
 * * Allowedvalueinconsistency generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "AllowedValueInconsistencyId"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_ALLOWEDVALUEINCONSISTENCY", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
public class AllowedValueInconsistency extends BaseEntity {
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "allowedValueId")
    private AllowedValue allowedValue;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "PROBLEMDESCRIPTIONID")
    private ProblemDescription problemDescription;
    @Getter
    @Setter
    private Boolean isTrue;
    @Getter
    @Setter
    @OneToMany(mappedBy = "allowedValueInconsistency")
    private Set<CrossRefInconsistency> crossRefInconsistencies;

    public AllowedValueInconsistency() {
    }

    public AllowedValueInconsistency(Long allowedValueInconsistencyId) {
        this.id = allowedValueInconsistencyId;
    }

    public AllowedValueInconsistency(Long allowedValueInconsistencyId, AllowedValue allowedValue,
                                     ProblemDescription problemdescriptionid, Boolean isTrue,
                                     Set<CrossRefInconsistency> crossRefInconsistencies) {
        super();
        this.id = allowedValueInconsistencyId;
        this.allowedValue = allowedValue;
        this.problemDescription = problemdescriptionid;
        this.isTrue = isTrue;
        this.crossRefInconsistencies = crossRefInconsistencies;
    }


}
