package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Calendar;
import java.util.Set;

/*
 * ComplianceCategory generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "COMPLIANCECATEGORYID"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_COMPLIANCECATEGORY", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
public class ComplianceCategory extends BaseEntity {
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name="SUPERCATEGORYID")
    private ComplianceSuperCategory complianceSuperCategory;
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    private BigDecimal standardPenaltyValue;
    @Getter
    @Setter
    private String penaltyLetterDesc;
    @Getter
    @Setter
    private String penaltyLetterDesc2;
    @Getter
    @Setter
    @OneToMany
    private Set<NytdError> errors;

    public ComplianceCategory() {
    }

    public ComplianceCategory(Long complianceCategoryid) {
        this.id = complianceCategoryid;
    }

    public ComplianceCategory(Long complianceCategoryId, ComplianceSuperCategory complianceSuperCategory,
                              String name, Calendar createdDate, String createdBy, Calendar updateDate, String updateBy,
                              String description, Set<NytdError> errors, String penaltyLetterDesc, String penaltyLetterDesc2) {
        this.id = complianceCategoryId;
        this.complianceSuperCategory = complianceSuperCategory;
        this.name = name;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.errors = errors;
        this.penaltyLetterDesc = penaltyLetterDesc;
        this.penaltyLetterDesc2 = penaltyLetterDesc2;
    }

}
