package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated Jul 15, 2009 11:56:32 AM by Hibernate Tools 3.2.4.GA


import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;

/*
 * * Crossrefinconsistency generated by hbm2java
 */
@Entity
public class CrossRefInconsistency extends BaseEntity
{
	@Getter @Setter
	private AllowedValueInconsistency allowedValueInconsistency;
	@Getter @Setter
	private AllowedValue allowedValue;
	@Getter @Setter
	private Boolean isTrue;
	
	public CrossRefInconsistency()
	{
	}

	public CrossRefInconsistency(Long crossRefInconsistencyId)
	{
		this.id = crossRefInconsistencyId;
	}

	/**
	 * @param crossRefInconsistencyId
	 * @param allowedValueInconsistency
	 * @param allowedvalueid
	 * @param istrue
	 */
	public CrossRefInconsistency(Long crossRefInconsistencyId,
			AllowedValueInconsistency allowedValueInconsistency, AllowedValue allowedvalueid, Boolean istrue)
	{
		super();
		this.id = crossRefInconsistencyId;
		this.allowedValueInconsistency = allowedValueInconsistency;
		this.allowedValue = allowedvalueid;
		this.isTrue = istrue;
	}


}
