package gov.hhs.acf.cb.nytds.persistence.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import java.util.HashSet;
import java.util.Set;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * DataAggregate generated by hbm2java
 */
@Entity
public class DataAggregate extends AggregateValue
{
	@Getter	@Setter
	private Lookup aggregateType;
	@Getter @Setter
	private Transmission transmission;
	@Getter @Setter
    private NonCompliance nonCompliance;
	@Getter @Setter
    private String complianceStatus;
	@Getter @Setter
    private Element element;
	@Getter @Setter
	private Set<AggregateValue> aggregateValues = new HashSet<>(0);

	public DataAggregate()
	{
	}

	public DataAggregate(Long dataAggregateId)
	{
		this.id = dataAggregateId;
	}

}
