package gov.hhs.acf.cb.nytds.persistence.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import java.util.HashSet;
import java.util.Set;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * DataAggregate generated by hbm2java
 */
@Entity
public class DataAggregate extends AggregateValue {
    @Getter
    @Setter
    @ManyToOne
    private Lookup aggregateType;
    @Getter
    @Setter
    @ManyToOne
    private Transmission transmission;
    @Getter
    @Setter
    @ManyToOne
    private NonCompliance nonCompliance;
    @Getter
    @Setter
    //@ManyToOne
    private String complianceStatus;
    @Getter
    @Setter
    @ManyToOne
    private Element element;
    @Getter
    @Setter
    @OneToMany
    private Set<AggregateValue> aggregateValues = new HashSet<>(0);

    public DataAggregate() {
    }

    public DataAggregate(Long dataAggregateId) {
        this.id = dataAggregateId;
    }

}
