package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * Datum generated by hbm2java
 */
@Entity
public class Datum extends BaseEntity
{
	@Getter	@Setter
	private Element element;
	@Getter @Setter
	private TransmissionRecord transmissionRecord;
	@Getter @Setter
	private String value;
	@Getter @Setter
	private String note;
	@Getter @Setter
	private Set<NonCompliance> nonCompliances = new HashSet<>(0);
	@Getter @Setter
	private Set<RecordLevelAdvisory> recordLevelDQA = new HashSet<>(0);

	public Datum()
	{
	}

	public Datum(Long datumid)
	{
		this.id = datumid;
	}

	public Datum(Long datumid, Element element, TransmissionRecord transmissionRecord,
			String value, Calendar createdDate, String createdBy, Calendar updateDate, String updateBy,
			String description, Set<NonCompliance> nonCompliances)
	{
		this.id = datumid;
		this.element = element;
		this.transmissionRecord = transmissionRecord;
		this.value = value;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.nonCompliances = nonCompliances;
	}


}
