package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Calendar;
import java.util.Set;

/*
 * Datum generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "DatumId"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_DATUM", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
public class Datum extends BaseEntity {
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "elementId")
    private Element element;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "transmissionRecordId")
    private TransmissionRecord transmissionRecord;
    @Getter
    @Setter
    private String value;
    @Getter
    @Setter
    private String note;
    @Getter
    @Setter
    @OneToMany(mappedBy = "datum")
    private Set<NonCompliance> nonCompliances;
// TODO mjk Figure this out!!!
    //    @Getter
//    @Setter
//    @OneToMany(mappedBy = "datum")
//    private Set<RecordLevelAdvisory> recordLevelDQA;

    public Datum() {
    }

    public Datum(Long datumid) {
        this.id = datumid;
    }

    public Datum(Long datumid, Element element, TransmissionRecord transmissionRecord,
                 String value, Calendar createdDate, String createdBy, Calendar updateDate, String updateBy,
                 String description, Set<NonCompliance> nonCompliances) {
        this.id = datumid;
        this.element = element;
        this.transmissionRecord = transmissionRecord;
        this.value = value;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.nonCompliances = nonCompliances;
    }


}
