package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * DerivedRole generated by hbm2java
 */
@Entity
public class DerivedRole extends BaseEntity {
    @Getter
    @Setter
    @ManyToOne
    private SecondaryUserRole secondaryUserRole;
    @Getter
    @Setter
    @ManyToOne
    private PrimaryUserRole primaryUserRole;
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    @ManyToMany
    private Set<Privilege> privileges = new HashSet<>(0);

    public DerivedRole() {
    }

    public DerivedRole(Long derivedRoleId) {
        this.id = derivedRoleId;
    }

    public DerivedRole(Long derivedRoleId, SecondaryUserRole secondaryUserRole,
                       PrimaryUserRole primaryUserRole, String name, Calendar createdDate, String createdBy,
                       Calendar updateDate, String updateBy, String description,
                       Set<Privilege> privileges) {
        this.id = derivedRoleId;
        this.secondaryUserRole = secondaryUserRole;
        this.primaryUserRole = primaryUserRole;
        this.name = name;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.privileges = privileges;
    }

}
