package gov.hhs.acf.cb.nytds.persistence.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Calendar;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * DueDate generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "dueDateId"))
public class DueDate extends BaseEntity {
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name="TRANSMISSIONTYPEID")
    private TransmissionType transmissionType;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name="REPORTINGPERIODID")
    private ReportingPeriod reportingPeriod;
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    private Calendar submissionDate;
    @Getter @Setter
    private Calendar adjustedDueDate;

    public DueDate() {
    }

    public DueDate(Long duedateid) {
        this.id = duedateid;
    }

    public DueDate(Long duedateid, TransmissionType transmissionType, ReportingPeriod reportingPeriod,
                   String name, Calendar submissionDate, Calendar createdDate, String createdBy, Calendar updateDate,
                   String updateBy, String description) {
        this.id = duedateid;
        this.transmissionType = transmissionType;
        this.reportingPeriod = reportingPeriod;
        this.name = name;
        this.submissionDate = submissionDate;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
    }

}
