package gov.hhs.acf.cb.nytds.persistence.entity;

//Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import java.util.Calendar;


/*
 * Lookup generated by hbm2java
 */
@Entity
public class Lookup extends BaseEntity {
    @Getter
    @Setter
    private String category;
    @Getter
    @Setter
    private Byte codeValue;
    @Getter
    @Setter
    private String codeDescription;
    @Getter
    @Setter
    private Short sortOrder;


    public Lookup() {
    }

    public Lookup(Long lookupId) {
        this.id = lookupId;
    }

    public Lookup(Long lookupId, String category, Byte codeValue, String codeDescription, Short sortOrder,
                  String createdBy, Calendar updateDate, String updateBy, String description) {
        this.id = lookupId;
        this.category = category;
        this.codeValue = codeValue;
        this.codeDescription = codeDescription;
        this.sortOrder = sortOrder;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
    }
}
