package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * Message generated by hbm2java
 */
@Entity
public class Message extends BaseEntity {
    // persistent properties
//    @Getter
//    @Setter
//    private Sender sender;
    @Getter
    @Setter
    private String subject;
    @Getter
    @Setter
    private String messageBody;
    @Getter
    @Setter
    @ManyToOne
    private SiteUser siteUser;
    @Getter
    @Setter
    @ManyToOne
    private Message parentMessage;
    @Getter
    @Setter
    @ManyToMany
    private Set<SiteUser> recipients;
    @Getter
    @Setter
    @OneToMany
    private Set<Message> repliedMessages = new HashSet<>(0);

    // transient properties
    @Getter
    @Setter
    private String messageFrom;
    @Getter
    @Setter
    private String messageAddressedTo;
    @Getter
    @Setter
    private String beforeSignatureWord;
    @Getter
    @Setter
    private String signature;
    @Getter
    @Setter
    private String messageCreatedDate;

    public Message() {
    }

    public Message(Long messageId) {
        this.id = messageId;
    }

    public Message(Long messageId, String subject,
                   Calendar createdDate, String createdBy,
                   Calendar updateDate, String updateBy, String description) {
        this.id = messageId;
        this.subject = subject;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
    }


}
