package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * Population generated by hbm2java
 */
@Entity
public class Population extends BaseEntity
{
	@Getter @Setter
	private String name;
	@Getter @Setter
	private String populationType;
	@Getter @Setter
	private Set<ElementPopulation> elementPopulations = new HashSet<>(0);
	@Getter @Setter
	private Set<AllowedValue> allowedValues = new HashSet<>(0);

	public Population()
	{
	}

	public Population(Long populationid)
	{
		this.id = populationid;
	}

	public Population(Long populationId, String name, Calendar createdDate, String createdBy,
			Calendar updateDate, String updateBy, String description, 
			Set<ElementPopulation> elementPopulations, Set<AllowedValue> allowedValues)
	{
		this.id = populationId;
		this.name = name;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.elementPopulations = elementPopulations;
		this.allowedValues = allowedValues;
	}
}
