package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * Privilege generated by hbm2java
 */
@Entity
public class Privilege extends BaseEntity {
    @Getter
    @Setter
    private String privilegeType;
    @Getter
    @Setter
    @ManyToMany
    private Set<DerivedRole> derivedRoles = new HashSet<>(0);

    public Privilege() {
    }

    public Privilege(Long privilegeId) {
        this.id = privilegeId;
    }

    public Privilege(Long privilegeId, String privilegeType, Calendar createdDate, String createdBy,
                     Calendar updateDate, String updateBy, String description,
                     Set<DerivedRole> derivedRoles) {
        this.id = privilegeId;
        this.privilegeType = privilegeType;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.derivedRoles = derivedRoles;
    }
}
