package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * ProblemDescription generated by hbm2java
 */
@Entity
public class ProblemDescription extends BaseEntity {
	@Getter	@Setter
	private Long problemDescriptionId;
	@Getter @Setter
	private String name;
	@Getter @Setter
	private Set<NytdError> errors = new HashSet<>(0);

	public ProblemDescription()
	{
	}

	public ProblemDescription(Long problemDescriptionId)
	{
		this.problemDescriptionId = problemDescriptionId;
	}

	public ProblemDescription(Long problemDescriptionId, String name, Calendar createdDate, String createdBy,
			Calendar updateDate, String updateBy, String description, Set<NytdError> errors)
	{
		this.problemDescriptionId = problemDescriptionId;
		this.name = name;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.errors = errors;
	}

}
