package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import java.util.Calendar;
import java.util.Set;

/*
 * ProblemDescription generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "PROBLEMDESCRIPTIONID"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_PROBLEMDESCRIPTION", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
public class ProblemDescription extends BaseEntity {
//    @Getter
//    @Setter
//    private Long problemDescriptionId;
    @Getter
    @Setter
    @Column(length = 1000)
    private String name;

    @Getter
    @Setter
    private Long complianceCategoryId;

    @Getter
    @Setter
    private String ruleName;

    @Getter
    @Setter
    @OneToMany(mappedBy = "problemDescription")
    private Set<NytdError> errors;

    public ProblemDescription() {
    }

//    public ProblemDescription(Long problemDescriptionId) {
//        this.problemDescriptionId = problemDescriptionId;
//    }

    public ProblemDescription(Long problemDescriptionId, String name, Calendar createdDate, String createdBy,
                              Calendar updateDate, String updateBy, String description, Set<NytdError> errors) {
        //this.problemDescriptionId = problemDescriptionId;
        this.name = name;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.errors = errors;
    }

}
