package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.OneToMany;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * Region generated by hbm2java
 */
@Entity
public class Region extends BaseEntity {
    @Getter
    @Setter
    private String region;
    @Getter
    @Setter
    private String regionCode;
    @Getter
    @Setter
    @OneToMany(mappedBy = "region")
    private Set<State> states = new HashSet<>(0);

    public Region() {
    }

    public Region(Long regionId) {
        this.id = regionId;
    }

    public Region(Long regionId, String region, String regionCode, Calendar createdDate, String createdBy,
                  Calendar updateDate, String updateBy, String description, Set<State> states) {
        this.id = regionId;
        this.region = region;
        this.regionCode = regionCode;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.states = states;
    }


    public String toString() {
        return "Region: " + region;
    }
}
