package gov.hhs.acf.cb.nytds.persistence.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import java.util.Calendar;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * AggregateLevelError generated by hbm2java
 */
@Entity
public class ServedPopulation extends Population {
    @Getter
    @Setter
    @ManyToOne
    private Population population;
    @Getter
    @Setter
    private String name;

    public ServedPopulation() {
    }

    public ServedPopulation(Long populationid) {
        this.id = populationid;
    }

    public ServedPopulation(Long populationid, Population population, String name, Calendar createdDate,
                            String createdBy, Calendar updateDate, String updateBy, String description) {
        this.id = populationid;
        this.population = population;
        this.name = name;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
    }
}
