package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * State generated by hbm2java
 */
@Entity
public class State extends BaseEntity
{
	@Getter	@Setter
	@ManyToOne
	private Region region;
	@Getter @Setter
	private String stateName;
	@Getter @Setter
	private String abbreviation;
	@Getter @Setter
	private String fipsCode;
	// TODO mjk Check if used, not mapped in hbm.xml
//	@Getter @Setter
//	private Set<PrimaryUserRole> primaryUserRoles = new HashSet<>(0);
//	@Getter @Setter
//	private Set<Transmission> transmissions  = new HashSet<>(0);

	public State()
	{
	}
	
	public State(Long stateId)
	{
		this.id = stateId;
	}

	public State(Region region, String stateName, String abbreviation, String fipsCode,
			Calendar createdDate, String createdBy, Calendar updateDate, String updateBy, String description,
			Set<PrimaryUserRole> primaryUserRoles, Set<Transmission> transmissions)
	{
		this.region = region;
		this.stateName = stateName;
		this.abbreviation = abbreviation;
		this.fipsCode = fipsCode;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
//		this.primaryUserRoles = primaryUserRoles;
//		this.transmissions = transmissions;
	}


    public String toString() {
        return "State: "+stateName;
    }
}
