package gov.hhs.acf.cb.nytds.persistence.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import java.util.Calendar;

// Generated Jun 1, 2009 2:40:24 PM by Hibernate Tools 3.2.4.GA

/*
 * Notes generated by hbm2java
 */
@Entity
public class TransmissionNote extends BaseEntity {
//    @Getter
//    @Setter
//    @ManyToOne
//    private Long transmissionNoteId;
    @Getter
    @Setter
    @ManyToOne
    private Transmission transmission;
    @Getter
    @Setter
    private String note;

    public TransmissionNote() {
    }


}
