package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import com.fasterxml.jackson.annotation.JsonBackReference;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Calendar;
import java.util.Set;

/*
 * TransmissionRecord generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "TransmissionRecordId"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_TRANSMISSIONRECORD", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
public class TransmissionRecord extends BaseEntity {
    @Getter
    @Setter
    @JsonBackReference
    @ManyToOne
    @JoinColumn(name = "transmissionId")
    private Transmission transmission;
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    private String recordNumber;
    @Getter
    @Setter
    private String notes;
    @Getter
    @Setter
    @ManyToOne
    //@JoinColumn(name = "populationId")
    private ServedPopulation servedPopulation;
    @Getter
    @Setter
    @ManyToOne
    //@JoinColumn(name = "populationId")
    private OutcomePopulation outcomePopulation;
    @Getter
    @Setter
    @OneToMany(mappedBy = "transmissionRecord")
    private Set<Datum> datums;

    public TransmissionRecord() {
    }

    public TransmissionRecord(Long transmissionRecordId) {
        this.id = transmissionRecordId;
    }

    public TransmissionRecord(Long transmissionRecordId, String name, String recordNumber, Calendar createdDate, String createdBy, Calendar updateDate,
                              String updateBy, String description, Set<Datum> datums) {
        this.id = transmissionRecordId;
        this.name = name;
        this.recordNumber = recordNumber;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.datums = datums;
    }


}
