package gov.hhs.acf.cb.nytds.persistence.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * TransmissionRecord generated by hbm2java
 */
@Entity
public class TransmissionRecord extends BaseEntity {
    @Getter
    @Setter
    @ManyToOne
    private Transmission transmission;
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    private String recordNumber;
    @Getter
    @Setter
    private String notes;
    @Getter
    @Setter
    @ManyToOne
    private ServedPopulation servedPopulation;
    @Getter
    @Setter
    @ManyToOne
    private OutcomePopulation outcomePopulation;
    @Getter
    @Setter
    @OneToMany
    private Set<Datum> datums = new HashSet<>(0);

    public TransmissionRecord() {
    }

    public TransmissionRecord(Long transmissionRecordId) {
        this.id = transmissionRecordId;
    }

    public TransmissionRecord(Long transmissionRecordId, String name, String recordNumber, Calendar createdDate, String createdBy, Calendar updateDate,
                              String updateBy, String description, Set<Datum> datums) {
        this.id = transmissionRecordId;
        this.name = name;
        this.recordNumber = recordNumber;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.datums = datums;
    }

}
