package gov.hhs.acf.cb.nytds.persistence.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import java.util.Calendar;

// Generated Jun 1, 2009 2:40:24 PM by Hibernate Tools 3.2.4.GA

/*
 * Notes generated by hbm2java
 */
@Entity
public class TransmissionNote extends BaseEntity
{
	@Getter	@Setter
	private Long transmissionNoteId;
	@Getter @Setter
	private Transmission transmission;
	@Getter @Setter
	private String note;

	public TransmissionNote()
	{
	}

	public TransmissionNote(Long noteId)
	{
		this.transmissionNoteId = noteId;
	}

	public TransmissionNote(Long transmissionNoteId, Transmission transmission, String note, Calendar createddate,
			String createdby, Calendar updatedate, String updateby, String description)
	{
		this.transmissionNoteId = transmissionNoteId;
		this.transmission = transmission;
		this.note = note;
	}

}
