package gov.hhs.acf.cb.nytds.persistence.component.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Calendar;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * AllowedValue generated by hbm2java
 */
@Entity
@Table(name="AllowedValue")
@AttributeOverride(name = "id", column = @Column(name = "ALLOWEDVALUEID"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_ALLOWEDVALUE", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
public class AllowedValue extends BaseEntity {
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "POPULATIONID")
    private Population population;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name="ELEMENTLEVELDQASTDID")
    private ElementLevelDQAStandard elementLevelDQAStandard;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name="ELEMENTID")
    private Element element;
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    private String value;
    @Getter
    @Setter
    private Long sortOrder;
    @Getter @Setter
    private String federalValue;

    public AllowedValue() {
    }

    public AllowedValue(Long allowedValueId) {
        this.id = allowedValueId;
    }

    public AllowedValue(Long allowedValueId, Population population, ElementLevelDQAStandard elementLevelDQAStandard, Element element, String name,
                        String value, Calendar createdDate, String createdBy, Calendar updateDate, String updateBy,
                        String description) {
        this.id = allowedValueId;
        this.population = population;
        //	this.dataQualityAdvStandard = dataQualityAdvStandard;
        this.elementLevelDQAStandard = elementLevelDQAStandard;
        this.element = element;
        this.name = name;
        this.value = value;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
    }

}
