package gov.hhs.acf.cb.nytds.persistence.component.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import java.util.Calendar;
import java.util.Set;

/*
 * ComplianceSuperCategory generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "ComplianceSuperCategoryId"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_COMPLIANCESUPERCATEGORY", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
public class ComplianceSuperCategory extends BaseEntity {
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    @OneToMany(mappedBy = "complianceSuperCategory")
    private Set<ComplianceCategory> complianceCategories;

    public ComplianceSuperCategory() {
    }

    public ComplianceSuperCategory(Long complianceSuperCategoryId) {
        this.id = complianceSuperCategoryId;
    }

    public ComplianceSuperCategory(Long complianceSuperCategoryId, String name, Calendar createdDate,
                                   String createdBy, Calendar updateDate, String updateBy, String description,
                                   Set<ComplianceCategory> complianceCategories) {
        this.id = complianceSuperCategoryId;
        this.name = name;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.complianceCategories = complianceCategories;
    }

}
