package gov.hhs.acf.cb.nytds.persistence.component.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Calendar;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * ComplianceStandard generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "ComplianceStandardId"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_COMPLIANCESTANDARD", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
public class ComplianceStandard extends BaseEntity {
    @Getter
    @Setter
    @OneToOne
    @JoinColumn(name = "elementId")
    private Element element;
    @Getter
    @Setter
    private Integer complianceStandard;
    @Getter
    @Setter
    private String penaltyLetterDesc;


    public ComplianceStandard() {
    }

    public ComplianceStandard(Long complianceStandardId) {
        this.id = complianceStandardId;
    }

    public ComplianceStandard(Long complianceStandardId, Element element, Integer complianceStandard,
                              Calendar createdDate, String createdBy, Calendar updateDate, String updateBy, String description,
                              String penaltyLetterDesc) {
        this.id = complianceStandardId;
        this.element = element;
        this.complianceStandard = complianceStandard;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.penaltyLetterDesc = penaltyLetterDesc;
    }


}
