package gov.hhs.acf.cb.nytds.persistence.component.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Calendar;
import java.util.Set;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * DataQualityAdvStandard generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "DataQualityAdvStandardId"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_DATAQUALITYADVAGGREGATE", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
public class DataQualityAdvStandard extends BaseEntity {
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    private Integer dataQualityAdvStandard;

    // associations
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "allowedValueId")
    private AllowedValue allowedValue;

    // collections
    @Getter
    @Setter
    @OneToMany(mappedBy = "dataQualityAdvStandard")
    private Set<DataQualityAdvAggregate> dataAggregates;

    public DataQualityAdvStandard() {
    }

    public DataQualityAdvStandard(Long dataQualityAdvStandardId) {
        this.id = dataQualityAdvStandardId;
    }

    public DataQualityAdvStandard(Long dataQualityAdvStandardId, String name,
                                  Calendar createdDate, String createdBy, Calendar updateDate, String updateBy, String description) {
        this.id = dataQualityAdvStandardId;
        // this.element = element;
        this.name = name;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
    }

}
