package gov.hhs.acf.cb.nytds.persistence.component.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Set;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * DataAggregate generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "DataAggregateId"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_DATAAGGREGATE", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
public class DataAggregate extends AggregateValue {
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "lookupId")
    private Lookup aggregateType;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "transmissionId")
    private Transmission transmission;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "nonComplianceId")
    private NonCompliance nonCompliance;
    @Getter
    @Setter
    //@ManyToOne
    private String complianceStatus;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "elementId")
    private Element element;
    @Getter
    @Setter
    @OneToMany
    private Set<AggregateValue> aggregateValues;

    public DataAggregate() {
    }

    public DataAggregate(Long dataAggregateId) {
        this.id = dataAggregateId;
    }

}
