package gov.hhs.acf.cb.nytds.persistence.component.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Calendar;
import java.util.Set;

/*
 * DerivedRole generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "DerivedRoleId"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_DERIVEDROLE", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
public class DerivedRole extends BaseEntity {
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "secondaryUserRoleId")
    private SecondaryUserRole secondaryUserRole;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "primaryUserRoleId")
    private PrimaryUserRole primaryUserRole;
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE })
    @JoinTable(name = "PRIVLEGEDERIVEDROLE",
            joinColumns = @JoinColumn(name = "DerivedRoleId"),
            inverseJoinColumns = @JoinColumn(name = "privilegeId"))
    private Set<Privilege> privileges;

    public DerivedRole() {
    }

    public DerivedRole(Long derivedRoleId) {
        this.id = derivedRoleId;
    }

    public DerivedRole(Long derivedRoleId, SecondaryUserRole secondaryUserRole,
                       PrimaryUserRole primaryUserRole, String name, Calendar createdDate, String createdBy,
                       Calendar updateDate, String updateBy, String description,
                       Set<Privilege> privileges) {
        this.id = derivedRoleId;
        this.secondaryUserRole = secondaryUserRole;
        this.primaryUserRole = primaryUserRole;
        this.name = name;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.privileges = privileges;
    }

}
