package gov.hhs.acf.cb.nytds.persistence.component.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Calendar;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * ElementPopulation generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "ElementPopulationId"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_ELEMENTPOPULATION", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
public class ElementPopulation extends BaseEntity {
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "populationId")
    private Population population;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "elementId")
    private Element element;

    public ElementPopulation() {
    }

    public ElementPopulation(Long elementPopulationId) {
        this.id = elementPopulationId;
    }

    public ElementPopulation(Long elementPopulationId, Population population, Element element,
                             Calendar createdDate, String createdBy, Calendar updateDate, String updateBy, String description) {
        this.id = elementPopulationId;
        this.population = population;
        this.element = element;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
    }

}
