package gov.hhs.acf.cb.nytds.persistence.component.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Calendar;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * DataQualityAdvStandard generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "ELEMENTLEVELDQASTDID"))
public class ElementLevelDQAStandard extends BaseEntityIdentity {
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    private Integer dataQualityAdvStandard;
    @Getter
    @Setter
    private String conditionalDescription;
    @Getter
    @Setter
    private String dataQualityAdvNotation;
    // associations
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "ALLOWEDVALUEID")
    private AllowedValue allowedValue;

    @Getter @Setter
    private String dqaText;

    public ElementLevelDQAStandard() {
    }

    public ElementLevelDQAStandard(Long elementLevelDQAStandardId) {
        this.id = elementLevelDQAStandardId;
    }

    public ElementLevelDQAStandard(Long dataQualityAdvStandardId, String name,
                                   Calendar createdDate, String createdBy, Calendar updateDate, String updateBy, String description) {
        this.id = dataQualityAdvStandardId;
        // this.element = element;
        this.name = name;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
    }

}
