package gov.hhs.acf.cb.nytds.persistence.component.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Calendar;
import java.util.Set;


/*
 * Compliance generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "NonComplianceId"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_NONCOMPLIANCE", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
public class NonCompliance extends BaseEntity {
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "datumId")
    private Datum datum;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "transmissionId")
    private Transmission transmission;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "lookupid")
    private Lookup complianceType;
    @Getter
    @Setter
    @OneToOne
    private DataAggregate dataAggregate;
    @Getter
    @Setter
    @OneToMany(mappedBy = "nonCompliance")
    private Set<NytdError> errors;

    public NonCompliance() {
    }

    public NonCompliance(Long nonComplianceId) {
        this.id = nonComplianceId;
    }

    public NonCompliance(Long nonComplianceId, Datum datum,
                         Transmission transmission, Lookup complianceType, DataAggregate dataAggregate,
                         Calendar createdDate, String createdBy, Calendar updateDate, String updateBy,
                         String description, Set<NytdError> errors) {
        this.id = nonComplianceId;
        this.datum = datum;
        this.transmission = transmission;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.errors = errors;
        this.complianceType = complianceType;
        this.dataAggregate = dataAggregate;
    }

}
