package gov.hhs.acf.cb.nytds.persistence.component.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Calendar;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * AggregateLevelError generated by hbm2java
 */
@Entity
@Table(name = "OUTCOMEPOPULATION")
@PrimaryKeyJoinColumn(name = "populationId")
public class OutcomePopulation extends Population {
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "populationID")
    private Population population;
    @Getter
    @Setter
    @Column(name = "NAME")
    private String name;

    public OutcomePopulation() {
    }

    public OutcomePopulation(Long populationid) {
        this.id = populationid;
    }

    public OutcomePopulation(Long populationid, Population population, String name, Calendar createdDate,
                             String createdBy, Calendar updateDate, String updateBy, String description) {
        this.id = populationid;
        //this.population = population;
        this.name = name;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
    }

}
