package gov.hhs.acf.cb.nytds.persistence.component.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import java.util.Calendar;
import java.util.Set;

/*
 * PrimaryUserRole generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "PRIMARYUSERROLEID"))
public class PrimaryUserRole extends BaseEntity {
    // TODO mjk not mapped in hbm.xml
//	@Getter	@Setter
//	private State state;
//	@Getter @Setter
//	private Region region;
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    private Boolean roleType;
    @Getter
    @Setter
    @OneToMany(mappedBy = "primaryUserRole")
    private Set<DerivedRole> derivedRoles;
    @Getter
    @Setter
    @OneToMany(mappedBy = "primaryUserRole")
    private Set<SiteUser> siteUsers;

    public PrimaryUserRole() {
    }

    public PrimaryUserRole(Long primaryUserRoleid) {
        this.id = primaryUserRoleid;
    }

    public PrimaryUserRole(Long primaryUserRoleId, State state, Region region, String name, Boolean roleType,
                           Calendar createdDate, String createdBy, Calendar updateDate, String updateBy, String description,
                           Set<DerivedRole> derivedRoles, Set<SiteUser> siteUsers) {
        this.id = primaryUserRoleId;
//		this.state = state;
//		this.region = region;
        this.name = name;
        this.roleType = roleType;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.derivedRoles = derivedRoles;
        this.siteUsers = siteUsers;
    }

}
