package gov.hhs.acf.cb.nytds.persistence.component.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import java.util.Calendar;
import java.util.Set;

/*
 * Privilege generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "PRIVILEGEID"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_PRIVILEGE", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
public class Privilege extends BaseEntity {
    @Getter
    @Setter
    private String privilegeType;
    @Getter
    @Setter
    @ManyToMany(mappedBy = "privileges")
    private Set<DerivedRole> derivedRoles;

    public Privilege() {
    }

    public Privilege(Long privilegeId) {
        this.id = privilegeId;
    }

    public Privilege(Long privilegeId, String privilegeType, Calendar createdDate, String createdBy,
                     Calendar updateDate, String updateBy, String description,
                     Set<DerivedRole> derivedRoles) {
        this.id = privilegeId;
        this.privilegeType = privilegeType;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.derivedRoles = derivedRoles;
    }
}
