package gov.hhs.acf.cb.nytds.persistence.component.entity;

/*
 * RecordLevelError generated by hbm2java
 */
public class RecordLevelError extends NytdError {
    public String formatErrorMessage() {
        String errorMsg = "Fix Me";
//        if (problemDescription == null) {
//            return "N/A";
//        }
//
//        Map<String, Object> namedParams = new HashMap<>();
//        Datum datum = nonCompliance.getDatum();
//        namedParams.put("elementNumber", datum.getElement().getId());
//        namedParams.put("datumValue",
//                datum.getValue() == null ? "Blank" : datum.getValue());
//        namedParams.put("referenceDatumValue", referenceDatumValue);
//        String errorMsg = problemDescription.formatText(
//                problemDescription.getName(), namedParams);
        return errorMsg;
    }
}
