package gov.hhs.acf.cb.nytds.persistence.component.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;
import java.util.Calendar;
import java.util.Set;

/*
 * Region generated by hbm2java
 */
@Entity
@Table(name = "REGION")
@AttributeOverride(name = "id", column = @Column(name = "regionId"))
@SequenceGenerator(name = "default_gen", sequenceName = "SEQ_REGION", allocationSize = BaseEntity.DEFAULT_SEQUENCE_ALLOCATION_SIZE)
@ToString
public class Region extends BaseEntity {
    @Getter
    @Setter(AccessLevel.PROTECTED)
    private String region;
    @Getter
    @Setter(AccessLevel.PROTECTED)
    private String regionCode;
    @OneToMany(mappedBy = "region")
    @Getter
    @Setter(AccessLevel.PROTECTED)
    private Set<State> states;

    public Region() {
    }

    public Region(Long regionId) {
        this.id = regionId;
    }

    public Region(Long regionId, String region, String regionCode, Calendar createdDate, String createdBy,
                  Calendar updateDate, String updateBy, String description, Set<State> states) {
        this.id = regionId;
        this.region = region;
        this.regionCode = regionCode;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.states = states;
    }


    @Override
    public String toString() {
        return "{\"Region\":"
                + super.toString()
                + ", \"id\":\"" + id + "\""
                + ", \"version\":\"" + version + "\""
                + ", \"createdDate\":" + createdDate
                + ", \"createdBy\":\"" + createdBy + "\""
                + ", \"updateDate\":" + updateDate
                + ", \"updateBy\":\"" + updateBy + "\""
                + ", \"description\":\"" + description + "\""
                + ", \"region\":\"" + region + "\""
                + ", \"regionCode\":\"" + regionCode + "\""
                + "}";
    }
}
