package gov.hhs.acf.cb.nytds.persistence.component.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import java.util.Set;

/*
 * SecondaryUserRole generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "SecondaryUserRoleId"))
public class SecondaryUserRole extends BaseEntity {
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    @OneToMany(mappedBy = "secondaryUserRole")
    private Set<DerivedRole> derivedRoles;
    @Getter
    @Setter
    @OneToMany(mappedBy = "secondaryUserRole")
    private Set<SiteUserSecondaryUserRole> siteUserSecondaryUserRoles;

    public SecondaryUserRole() {
    }

    public SecondaryUserRole(Long secondaryUserRoleId) {
        this.id = secondaryUserRoleId;
    }

    public interface Client {
        String getName();

        Set<DerivedRole> getDerivedRoles();

        Set<SiteUserSecondaryUserRole> getSiteUserSecondaryUserRoles();
    }

}
