package gov.hhs.acf.cb.nytds.persistence.component.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import java.util.Calendar;
import java.util.Set;

/*
 * TransmissionType generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "TransmissionTypeId"))
public class TransmissionType extends BaseEntity {
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    @OneToMany(mappedBy = "transmissionType")
    private Set<Transmission> transmissions;
    @Getter
    @Setter
    @OneToMany(mappedBy = "transmissionType")
    private Set<DueDate> dueDates;

    public TransmissionType() {
    }

    public TransmissionType(Long transmissionTypeId) {
        this.id = transmissionTypeId;
    }

    public TransmissionType(Long transmissionTypeId, String name, Calendar createdDate, String createdBy,
                            Calendar updateDate, String updateBy, String description, Set<Transmission> transmissions,
                            Set<DueDate> dueDates) {
        this.id = transmissionTypeId;
        this.name = name;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.transmissions = transmissions;
        this.dueDates = dueDates;
    }

}
