package gov.hhs.acf.cb.nytds.persistence.component.entity;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Calendar;
import java.util.Set;

/*
 * Transmission generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "TransmissionId"))
public class Transmission extends BaseEntity {
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "TransmissionTypeId")
    private TransmissionType transmissionType;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "reportingPeriodId")
    private ReportingPeriod reportingPeriod;
    @Getter
    @Setter
    private String name;
    @Getter
    @Setter
    private String fileGenerationDate;
    @Getter
    @Setter
    private String fileId;
    @Getter
    @Setter
    private String complianceStatus;
    @Getter
    @Setter
    @Column(name = "PROCESSINGSTATUS")
    private String processingStatus;
    @Getter
    @Setter
    private String submissionStatus;
    @Getter
    @Setter
    private Calendar submittedDate;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "siteUserId")
    private SiteUser siteUser;
    @Getter
    @Setter
    private String fileName;
    @Getter
    @Setter
    private Integer fileSize;
    @Getter
    @Setter
    private Calendar fileReceivedDate;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "stateId")
    private State state;
    @Getter
    @Setter
    @Column(name = "DATAFILEREPORTDATEVALUE")
    private String dataFileReportPeriodValue;
    @Getter
    @Setter
    @Column(name = "DATAFILESTATEVALUE")
    private String dataFileStateValue; // Transmission Category value in data file
    @Getter
    @Setter
    @Column(name = "DATAFILETRANSMISSIONTYPEVALUE")
    private String dataFileTransmissionTypeValue;
    @Getter
    @Setter
    private String lateWarningMessage;
    @Getter
    @Setter
    private BigDecimal potentialPenalty;
    @Getter
    @Setter
    @Column(name = "IMPROPERFORMATTEDVALCNT")
    private Long improperFormattedValCnt;
    @Getter
    @Setter
    @Column(name = "DUPLICATERECORDSCNT")
    private Long duplicateRecordsCnt;
    @Getter
    @Setter
    private Long formatErrCnt;
    @Getter
    @Setter
    @Column(name = "RECORDCOUNT")
    private Long recordsCnt;
    @Getter
    @Setter
    @OneToMany(mappedBy = "transmission")
    private Set<NonCompliance> nonCompliances;
    @Getter
    @Setter
    @OneToMany(mappedBy = "transmission")
    private Set<TransmissionNote> transmissionNotes;
    @Getter
    @Setter
    @OneToMany(mappedBy = "transmission")
    private Set<ElementNote> elementNotes;
    @Getter
    @Setter
    @OneToMany(mappedBy = "transmission")
    private Set<TransmissionRecord> transmissionRecords;
    @Getter
    @Setter
    @OneToMany(mappedBy = "transmission")
    private Set<DataAggregate> dataAggregates;

    // Check these against the hbm files.

    @Getter
    @Setter
    private Long xmlDataId;

    @Getter
    @Setter
    @Column(name = "PROCESSEDSTATUS")
    private String processedStatus;

    @Getter
    @Setter
    @Column(name = "DATVALUECOMPLIANTCNT")
    private Long datvaluecompliantcnt;

    @Getter
    @Setter
    @Column(name = "DATVALUEDATQUALADVISCNT")
    private Long datvaluedatqualadviscnt;

    @Getter
    @Setter
    @Column(name = "TIMELYERRCNT")
    private Long timelyerrcnt;

    @Getter
    @Setter
    @Column(name = "RECORDLEVELERRCNT")
    private Long recordlevelerrcnt;

    @Getter
    @Setter
    @Column(name = "TRANSMISSIONLEVELERRCNT")
    private Long transmissionlevelerrcnt;


    @Getter
    @Setter
    @Column(name = "PROCESSINGEXCEPTION")
    private String processingexception;

    /////////////////////////////////////////////////
    @Getter
    @Setter
    @Column(name = "RECORDLEVELDQACNT")
    private Long recordleveldqacnt;

    @Getter
    @Setter
    @Column(name = "ELEMENTLEVELDQACNT")
    private Long elementleveldqacnt;

    @Getter
    @Setter
    @Column(name = "RECORDSINERRORCNT")
    private Long recordsinerrorcnt;








    public Transmission() {
    }

    public Transmission(Long transmissionId) {
        this.id = transmissionId;
    }

    public Transmission(Long transmissionId, TransmissionType transmissionType, ReportingPeriod reportingPeriod,
                        String name, Calendar createdDate, String createdBy, Calendar updateDate, String updateBy, String description,
                        Set<NonCompliance> nonCompliances, String submissionStatus, Calendar submittedDate, SiteUser siteUser,
                        String fileName, Integer fileSize, Calendar fileReceivedDate, State state) {
        this.id = transmissionId;
        this.transmissionType = transmissionType;
        this.reportingPeriod = reportingPeriod;
        this.name = name;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
        this.nonCompliances = nonCompliances;
        this.submissionStatus = submissionStatus;
        this.submittedDate = submittedDate;
        this.siteUser = siteUser;
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.fileReceivedDate = fileReceivedDate;
        this.state = state;

    }


    /**
     * Informs caller of any transmission errors in the current transmission.
     *
     * @return
     */
    public boolean hasNoErrorsInTransmission() {

        return (getImproperFormattedValCnt() == null || (getImproperFormattedValCnt() != null
                && getImproperFormattedValCnt() == 0))
                && (getFormatErrCnt() == null || (getFormatErrCnt() != null
                && getFormatErrCnt() == 0));
    }

    /**
     * Checks duplicate records have been counted.
     *
     * @return
     */
    public boolean hasDuplicateRecords() {
        return (getDuplicateRecordsCnt() != null && getDuplicateRecordsCnt() > 0)
                && (getImproperFormattedValCnt() == null || (getImproperFormattedValCnt() != null
                && getImproperFormattedValCnt() == 0));
    }

    /**
     * Checks if any file format errors have been counted.
     *
     * @return
     */
    public boolean hasFileFormatErrors() {
        return (getDuplicateRecordsCnt() != null && getDuplicateRecordsCnt() > 0)
                && (getImproperFormattedValCnt() != null && getImproperFormattedValCnt() > 0);
    }
}
