package gov.hhs.acf.cb.nytds.persistence.entity.helper;

import gov.hhs.acf.cb.nytds.persistence.entity.BaseEntityIdentity;
import gov.hhs.acf.cb.nytds.util.DateUtil;

import java.math.BigDecimal;
import java.util.Calendar;
import java.util.TimeZone;

// Generated Jun 10, 2009 3:28:47 PM by Hibernate Tools 3.2.4.GA
/*
 * Vwtransmissionstatus generated by hbm2java
 */
@SuppressWarnings("serial")
public class VwTransmissionStatus extends BaseEntityIdentity
{
	private Long transmissionId;
	private Calendar submittedDate;
	private String fileGenerationDate;
	private Calendar fileReceivedDate;
	private String reportingPeriod;
	private Calendar endReportingDate;
	private String transmissionType;
	private BigDecimal potentialPenalty;
	private BigDecimal dataStandardPenalty;
	private BigDecimal fileStandardPenalty;
	private String state;
	private String region;
	private BigDecimal datValueCompliantCnt;
	private BigDecimal datValueDataQualtyAdvisCnt;
	private BigDecimal timelyErrCnt;
	private BigDecimal formatErrCnt;
	private BigDecimal recordLevelErrCnt;
	private BigDecimal transmissionLevelErrCnt;
	private String strFileReceivedDate;
	private String strSubmittedDate;
	private String complianceStatus;
	private String submissionStatus;
	private BigDecimal numberOfRecordsInFile;
	private String fileName;
	private String description;
	private String processingStatus;
	private String stateAbbr;
	//private String xmlTransmissionType;
	private String dataFileTransmissionTypeValue;
	private Long improperFormattedValCnt;
	private Integer elementLevelDQACnt;
	private Integer recordLevelDQACnt;
	public VwTransmissionStatus()
	{
	}

	/*
	 * 
	 */
	public VwTransmissionStatus(Long transmissionId)
	{
		this.transmissionId = transmissionId;
	}

	public VwTransmissionStatus(Long transmissionId, Boolean status, Calendar submittedDate,
			String fileGenerationDate, Calendar fileReceivedDate, String reportingPeriod,
			Calendar endReportingDate, String transmissionType, BigDecimal potentialPenalty, String state,
			String region, BigDecimal datValueCompliantCnt, BigDecimal datValueDataQualtyAdvisCnt,
			BigDecimal timelyErrCnt, BigDecimal formatErrCnt,BigDecimal fileStandardPenalty)
	{
		this.transmissionId = transmissionId;
		this.submittedDate = submittedDate;
		this.fileGenerationDate = fileGenerationDate;
		this.fileReceivedDate = fileReceivedDate;
		this.reportingPeriod = reportingPeriod;
		this.endReportingDate = endReportingDate;
		this.transmissionType = transmissionType;
		this.potentialPenalty = potentialPenalty;
		this.state = state;
		this.region = region;
		this.datValueCompliantCnt = datValueCompliantCnt;
		this.datValueDataQualtyAdvisCnt = datValueDataQualtyAdvisCnt;
		this.timelyErrCnt = timelyErrCnt;
		this.formatErrCnt = formatErrCnt;
		this.fileStandardPenalty = fileStandardPenalty;
	}

	public Long getTransmissionId()
	{
		return this.transmissionId;
	}

	public void setTransmissionId(Long transmissionid)
	{
		this.transmissionId = transmissionid;
	}

	public Calendar getSubmittedDate()
	{
		return this.submittedDate;
	}

	public void setSubmittedDate(Calendar submittedDate)
	{
		this.submittedDate = submittedDate;
	}

	/**
	 * @return the fileGenerationDate
	 */
	public String getFileGenerationDate()
	{
		return fileGenerationDate;
	}

	/**
	 * @param fileGenerationDate
	 *           the fileGenerationDate to set
	 */
	public void setFileGenerationDate(String fileGenerationDate)
	{
		this.fileGenerationDate = fileGenerationDate;
	}

	public Calendar getFileReceivedDate()
	{
		return this.fileReceivedDate;
	}

	public void setFileReceivedDate(Calendar fileReceivedDate)
	{
		this.fileReceivedDate = fileReceivedDate;
	}

	public String getReportingPeriod()
	{
		return this.reportingPeriod;
	}

	public void setReportingPeriod(String reportingPeriod)
	{
		this.reportingPeriod = reportingPeriod;
	}

	public Calendar getEndReportingDate()
	{
		return this.endReportingDate;
	}

	public void setEndReportingDate(Calendar endReportingDate)
	{
		this.endReportingDate = endReportingDate;
	}

	public String getTransmissionType()
	{
		return this.transmissionType;
	}

	public void setTransmissionType(String transmissionType)
	{
		this.transmissionType = transmissionType;
	}

	public BigDecimal getPotentialPenalty()
	{
		return this.potentialPenalty;
	}

	public void setPotentialPenalty(BigDecimal potentialPenalty)
	{
		this.potentialPenalty = potentialPenalty;
	}

	public String getState()
	{
		return this.state;
	}

	public void setState(String state)
	{
		this.state = state;
	}

	public String getRegion()
	{
		return this.region;
	}

	public void setRegion(String region)
	{
		this.region = region;
	}

	public BigDecimal getDatValueCompliantCnt()
	{
		return this.datValueCompliantCnt;
	}

	public void setDatValueCompliantCnt(BigDecimal datValueCompliantCnt)
	{
		this.datValueCompliantCnt = datValueCompliantCnt;
	}

	/**
	 * @return the datValueDataQualtyAdvisCnt
	 */
	public BigDecimal getDatValueDataQualtyAdvisCnt()
	{
		return datValueDataQualtyAdvisCnt;
	}

	/**
	 * @param datValueDataQualtyAdvisCnt
	 *           the datValueDataQualtyAdvisCnt to set
	 */
	public void setDatValueDataQualtyAdvisCnt(BigDecimal datValueDataQualtyAdvisCnt)
	{
		this.datValueDataQualtyAdvisCnt = datValueDataQualtyAdvisCnt;
	}

	public BigDecimal getTimelyErrCnt()
	{
		return this.timelyErrCnt;
	}

	public void setTimelyErrCnt(BigDecimal timelyErrCnt)
	{
		this.timelyErrCnt = timelyErrCnt;
	}

	public BigDecimal getFormatErrCnt()
	{
		return this.formatErrCnt;
	}

	public void setFormatErrCnt(BigDecimal formatErrCnt)
	{
		this.formatErrCnt = formatErrCnt;
	}

	/**
	 * @return the strFileReceivedDate
	 */
	public String getStrFileReceivedDate()
	{
		Calendar tempFileReceivedDate = fileReceivedDate;
		tempFileReceivedDate.setTimeZone(TimeZone.getTimeZone("America/New_York"));
		strFileReceivedDate = DateUtil.getHourMintueSecondWithTimeZone(tempFileReceivedDate);

		return strFileReceivedDate;
	}

	/**
	 * @return the strFileSubmittedDateTime
	 */
	public String getStrSubmissionDateTime()
	{
		Calendar tempFileReceivedDate = submittedDate;
		tempFileReceivedDate.setTimeZone(TimeZone.getTimeZone("America/New_York"));
		strSubmittedDate = DateUtil.getHourMintueSecondWithTimeZone(tempFileReceivedDate);
		return strSubmittedDate;
	}

	/**
	 * @return the recordLevelErrCnt
	 */
	public BigDecimal getRecordLevelErrCnt()
	{
		return recordLevelErrCnt;
	}

	/**
	 * @param recordLevelErrCnt
	 *           the recordLevelErrCnt to set
	 */
	public void setRecordLevelErrCnt(BigDecimal recordLevelErrCnt)
	{
		this.recordLevelErrCnt = recordLevelErrCnt;
	}

	/**
	 * @return the transmissionLevelErrCnt
	 */
	public BigDecimal getTransmissionLevelErrCnt()
	{
		return transmissionLevelErrCnt;
	}

	/**
	 * @param transmissionLevelErrCnt
	 *           the transmissionLevelErrCnt to set
	 */
	public void setTransmissionLevelErrCnt(BigDecimal transmissionLevelErrCnt)
	{
		this.transmissionLevelErrCnt = transmissionLevelErrCnt;
	}

	/**
	 * @return the strSubmittedDate
	 */
	public String getStrSubmittedDate()
	{
		return strSubmittedDate;
	}

	/**
	 * @param strSubmittedDate
	 *           the strSubmittedDate to set
	 */
	public void setStrSubmittedDate(String strSubmittedDate)
	{
		this.strSubmittedDate = strSubmittedDate;
	}

	/**
	 * @param strFileReceivedDate
	 *           the strFileReceivedDate to set
	 */
	public void setStrFileReceivedDate(String strFileReceivedDate)
	{
		this.strFileReceivedDate = strFileReceivedDate;
	}

	/**
	 * @return the numberOfRecordsInFile
	 */
	public BigDecimal getNumberOfRecordsInFile()
	{
		return numberOfRecordsInFile;
	}

	/**
	 * @param numberOfRecordsInFile
	 *           the numberOfRecordsInFile to set
	 */
	public void setNumberOfRecordsInFile(BigDecimal numberOfRecordsInFile)
	{
		this.numberOfRecordsInFile = numberOfRecordsInFile;
	}

	/**
	 * @return the currentSubmissionStatus
	 */
	public String getSubmissionStatus()
	{
		return submissionStatus;
	}

	/**
	 * @param submissionStatus
	 *           the currentSubmissionStatus to set
	 */
	public void setSubmissionStatus(String submissionStatus)
	{
		this.submissionStatus = submissionStatus;
	}

	/**
	 * @return the fileName
	 */
	public String getFileName()
	{
		return fileName;
	}

	/**
	 * @param fileName
	 *           the fileName to set
	 */
	public void setFileName(String fileName)
	{
		this.fileName = fileName;
	}

	/**
	 * @return the description
	 */
	@Override
	public String getDescription()
	{
		return description;
	}

	/**
	 * @param description
	 *           the description to set
	 */
	@Override
	public void setDescription(String description)
	{
		this.description = description;
	}

	/**
	 * @return the processingStatus
	 */
	public String getProcessingStatus()
	{
		return processingStatus;
	}

	/**
	 * @param processingStatus
	 *           the processingStatus to set
	 */
	public void setProcessingStatus(String processingStatus)
	{
		this.processingStatus = processingStatus;
	}

	/**
	 * @return the stateAbbr
	 */
	public String getStateAbbr()
	{
		return stateAbbr;
	}

	/**
	 * @param stateAbbr
	 *           the stateAbbr to set
	 */
	public void setStateAbbr(String stateAbbr)
	{
		this.stateAbbr = stateAbbr;
	}

	public String getComplianceStatus()
	{
		return complianceStatus;
	}

	public void setComplianceStatus(String complianceStatus)
	{
		this.complianceStatus = complianceStatus;
	}

	public String toString()
	{
		return getClass().getSimpleName() + "<" + Integer.toHexString(System.identityHashCode(this)) + ">"
				+ " id=" + getTransmissionId();
	}

	/**
	 * @return the xmlTransmissionType
	 */
	/*public String getXmlTransmissionType()
	{
		return xmlTransmissionType;
	}*/

	/**
	 * @param xmlTransmissionType the xmlTransmissionType to set
	 */
/*	public void setXmlTransmissionType(String xmlTransmissionType)
	{
		this.xmlTransmissionType = xmlTransmissionType;
	}*/

	/**
	 * @return the improperFormattedValCnt
	 */
	public Long getImproperFormattedValCnt()
	{
		return improperFormattedValCnt;
	}

	/**
	 * @param improperFormattedValCnt the improperFormattedValCnt to set
	 */
	public void setImproperFormattedValCnt(Long improperFormattedValCnt)
	{
		this.improperFormattedValCnt = improperFormattedValCnt;
	}

	/**
	 * @return the dataFileTransmissionTypeValue
	 */
	public String getDataFileTransmissionTypeValue()
	{
		return dataFileTransmissionTypeValue;
	}

	/**
	 * @param dataFileTransmissionTypeValue the dataFileTransmissionTypeValue to set
	 */
	public void setDataFileTransmissionTypeValue(String dataFileTransmissionTypeValue)
	{
		this.dataFileTransmissionTypeValue = dataFileTransmissionTypeValue;
	}

	/**
	 * @return the elementLevelDQACnt
	 */
	public Integer getElementLevelDQACnt()
	{
		return elementLevelDQACnt;
	}

	/**
	 * @param elementLevelDQACnt the elementLevelDQACnt to set
	 */
	public void setElementLevelDQACnt(Integer elementLevelDQACnt)
	{
		this.elementLevelDQACnt = elementLevelDQACnt;
	}

	/**
	 * @return the recordLevelDQACnt
	 */
	public Integer getRecordLevelDQACnt()
	{
		return recordLevelDQACnt;
	}

	/**
	 * @param recordLevelDQACnt the recordLevelDQACnt to set
	 */
	public void setRecordLevelDQACnt(Integer recordLevelDQACnt)
	{
		this.recordLevelDQACnt = recordLevelDQACnt;
	}

	public BigDecimal getDataStandardPenalty() {
		return dataStandardPenalty;
	}

	public void setDataStandardPenalty(BigDecimal dataStandardPenalty) {
		this.dataStandardPenalty = dataStandardPenalty;
	}

	/**
	 * @return the fileStandardPenalty
	 */
	public BigDecimal getFileStandardPenalty() {
		return fileStandardPenalty;
	}

	/**
	 * @param fileStandardPenalty the fileStandardPenalty to set
	 */
	public void setFileStandardPenalty(BigDecimal fileStandardPenalty) {
		this.fileStandardPenalty = fileStandardPenalty;
	}
}
