package gov.hhs.acf.cb.nytds.persistence.service.entity;

/*
 * AggregateLevelError generated by hbm2java
 */
public class AggregateLevelError extends NytdError {
    public String formatErrorMessage() {
        String errorMsg = "Some Error Message that Needs to be fixed";
        return errorMsg;
    }
}
