package gov.hhs.acf.cb.nytds.persistence.service.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Calendar;

// Generated Jun 1, 2009 2:40:24 PM by Hibernate Tools 3.2.4.GA

/*
 * Notes generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "ElementNoteId"))
public class ElementNote extends BaseEntity {
    @Getter
    @Setter
    private Long elementNoteId;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "elementId")
    private Element element;
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "id")
    private Transmission transmission;
    @Getter
    @Setter
    private String note;

    public ElementNote() {
    }

    public ElementNote(Long noteId) {
        this.elementNoteId = noteId;
    }

    public ElementNote(Long elementNoteId, Element element, Transmission transmission, String note, Calendar createddate,
                       String createdby, Calendar updatedate, String updateby, String description) {
        this.elementNoteId = elementNoteId;
        this.element = element;
        this.transmission = transmission;
        this.note = note;
    }

}
