package gov.hhs.acf.cb.nytds.persistence.service.entity;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

// Generated Jun 1, 2009 2:40:24 PM by Hibernate Tools 3.2.4.GA

/*
 * Notes generated by hbm2java
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "TransmissionNoteId"))
public class TransmissionNote extends BaseEntity {
    @Getter
    @Setter
    @ManyToOne
    @JoinColumn(name = "transmissionId")
    private Transmission transmission;
    @Getter
    @Setter
    private String note;

    public TransmissionNote() {
    }


}
